### ISSUE TITLE
Problem with test files. AttributeError: module 'py_audio2face.audio2face' has no attribute 'requests'

### ISSUE THREAD

**Issue by Eggwardhan** [SocAIty/py_audio2face#10]
when I run the " python .\tests\test_audio2face.py", it shows:"""

BlendShape Export failed: <MagicMock name='export_blend_shape().__getitem__()' id='1985979944736'>
F..EE
======================================================================        
ERROR: test_start_headless_server_success (__main__.TestAudio2Face.test_start_headless_server_success)
----------------------------------------------------------------------        
Traceback (most recent call last):
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1387, in patched
    with self.decoration_helper(patched,
  File "C:\Users\ss\miniconda3\Lib\contextlib.py", line 137, in __enter__  
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1369, in decoration_helper
    arg = exit_stack.enter_context(patching)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\contextlib.py", line 526, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1442, in __enter__
    self.target = self.getter()
                  ^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\pkgutil.py", line 528, in resolve_name  
    result = getattr(result, p)
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'py_audio2face.audio2face' has no attribute 'requests' 

======================================================================        
ERROR: test_start_headless_server_timeout (__main__.TestAudio2Face.test_start_headless_server_timeout)
----------------------------------------------------------------------        
Traceback (most recent call last):
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1387, in patched
    with self.decoration_helper(patched,
  File "C:\Users\ss\miniconda3\Lib\contextlib.py", line 137, in __enter__  
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1369, in decoration_helper
    arg = exit_stack.enter_context(patching)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\contextlib.py", line 526, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1442, in __enter__
    self.target = self.getter()
                  ^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\pkgutil.py", line 528, in resolve_name  
    result = getattr(result, p)
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'py_audio2face.audio2face' has no attribute 'requests' 

======================================================================        
FAIL: test_audio2face_single_with_sample_file (__main__.TestAudio2Face.test_audio2face_single_with_sample_file)
----------------------------------------------------------------------        
Traceback (most recent call last):
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 1390, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py_audio2face\tests\test_audio2face.py", line 52, in test_audio2face_single_with_sample_file
    mock_set_root_path.assert_called_once_with('test_files')
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 956, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ss\miniconda3\Lib\unittest\mock.py", line 944, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: set_root_path('test_files')
  Actual: set_root_path('test_files/test_audio_0.wav')

----------------------------------------------------------------------        
Ran 5 tests in 2.057s

FAILED (failures=1, errors=2)"""

**Comment by w4hns1nn** [comment]
Hey, Eggwardhan.

the test file is a unit test written with github copilot based on a simple "test_function"; but was never run before.
So you can ignore this error. Just use the library as explained as in the readme file.
If you want to do an favor to the community, im sure it appreciates the effort to write a working unit test.

Thanks
