### ISSUE TITLE
Using other arkkit heads like claire

### ISSUE THREAD

**Issue by yiouyou** [SocAIty/py_audio2face#8]
The error situation is as below:

1. claire_solved_arkit.usd is loaded. The reason I don't use mark_solved_arkit.usd as in the tutorial video is that I keep failing to download it from s3.
<img width="1920" alt="无标题" src="https://github.com/user-attachments/assets/c429070f-d564-4327-986c-69b2f509c881">

2. I'm not sure whether or not this issue causes the below error.
```
(venv) PS E:\_Ai\py_audio2face> python .\tests\test.py
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
starting audio2face headless
wait until audio2face is ready
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
API http://localhost:8011/status call error: Expecting value: line 1 column 1 (char 0)
status timeout
API http://localhost:8011/A2F/GetInstances call error: Expecting value: line 1 column 1 (char 0)
load scene E:\_Ai\py_audio2face\venv\Lib\site-packages\py_audio2face\assets\mark_arkit_solved_default.usd
Response of API http://localhost:8011/A2F/USD/Load is not JSON format. Intended?
Response of API http://localhost:8011/A2F/A2E/SetSettings is not JSON format. Intended?
Response of API http://localhost:8011/A2F/A2E/SetEmotion is not JSON format. Intended?
Response of API http://localhost:8011/A2F/Player/SetRootPath is not JSON format. Intended?
Response of API http://localhost:8011/A2F/Player/SetTrack is not JSON format. Intended?
Response of API http://localhost:8011/A2F/Exporter/ExportBlendshapes is not JSON format. Intended?
Traceback (most recent call last):
  File "E:\_Ai\py_audio2face\tests\test.py", line 39, in <module>
    test_file_methods()
  File "E:\_Ai\py_audio2face\tests\test.py", line 17, in test_file_methods
    preset_emotion_animation = a2f.audio2face_single(
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_Ai\py_audio2face\venv\Lib\site-packages\py_audio2face\audio2face.py", line 94, in audio2face_single
    return self.export(output_path=output_path, fps=fps, emotion_auto_detect=emotion_auto_detect)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_Ai\py_audio2face\venv\Lib\site-packages\py_audio2face\modules\_export.py", line 41, in export
    if 'status' not in response or response['status'] == 'ERROR':
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by w4hns1nn** [comment]
Hi,
the script checks at the biginning, if NVIDIA audio2face headless server is running under localhost by calling the "status" endpoint of audio2face. This already seems to fail..
Can you provide more information, how you installed it and about your working environment?
Why does the module try to download mark from S3?

**Comment by w4hns1nn** [comment]
Closed due missing activity.
